### PR TITLE
Improve URL example

### PR DESCRIPTION
**Pull request by matthewfeickert**
Add better examples dealing with remote URLs

### CODE REVIEW

**Comment by kratsg** [comment]
Gotta be careful with the URLs because anyone with that token can access the entire private repository..

**Comment by matthewfeickert** [comment]
> Gotta be careful with the URLs because anyone with that token can access the entire private repository.

I don't think this is true. I think that token is file specific. For example, if I take the token from one of the files I show and then use it for another file in the same region it 404's. So I think this is _only_ exposing those two files, which beyond the example, can't be used to gain any further information (beyond the background only).

If I'm wrong though, please message me and I'll go do what I can to delete things.

**Comment by kratsg** [comment]
Don't provide the URLs. You can use them, but you can't show them for other people to use... it's not public yet.

**Comment by matthewfeickert** [comment]
The notebook is scrubbed from the commit history now. With the exception of this PR page, but I don't think that is fixable.

**Pull request merged**
